# Generated by Django 4.1.7 on 2023-04-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
