# Generated by Django 4.1.7 on 2023-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_remove_americanasale_subcategoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alemanaschecasaustriacasale',
            name='subCategoria',
        ),
        migrations.RemoveField(
            model_name='alemanaschecasaustriacaslager',
            name='subCategoria',
        ),
        migrations.RemoveField(
            model_name='americanaslager',
            name='subCategoria',
        ),
        migrations.RemoveField(
            model_name='belgasfrancesasale',
            name='subCategoria',
        ),
        migrations.RemoveField(
            model_name='britanicasale',
            name='subCategoria',
        ),
        migrations.RemoveField(
            model_name='internacionalesale',
            name='subCategoria',
        ),
        migrations.RemoveField(
            model_name='internacionaleslager',
            name='subCategoria',
        ),
        migrations.RemoveField(
            model_name='otras',
            name='subCategoria',
        ),
        migrations.AddField(
            model_name='alemanaschecasaustriacasale',
            name='emailDeContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alemanaschecasaustriacasale',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alemanaschecasaustriacasale',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='alemanaschecasaustriacaslager',
            name='emailDeContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alemanaschecasaustriacaslager',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alemanaschecasaustriacaslager',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='americanaslager',
            name='emailDeContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='americanaslager',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='americanaslager',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='belgasfrancesasale',
            name='emailDeContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='belgasfrancesasale',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='belgasfrancesasale',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='britanicasale',
            name='emailDeContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='britanicasale',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='britanicasale',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='internacionalesale',
            name='emailDeContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internacionalesale',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='internacionalesale',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='internacionaleslager',
            name='emailDeContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internacionaleslager',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='internacionaleslager',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='otras',
            name='emailDeContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='otras',
            name='fechaDePublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='otras',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='americanasale',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
