# Generated by Django 4.1.7 on 2023-04-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0003_remove_alemanaschecasaustriacasale_subcategoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
