# Generated by Django 4.1.7 on 2023-04-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0005_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
